[package]
name = "llfree"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = { version = "0.2", optional = true }
bitfield-struct = "0.5"
log = { version = "0.4", default-features = false }
env_logger = { version = "0.10", default-features = false, optional = true }

[build-dependencies]
glob = "0.3"

[features]
default = ["std"]
std = ["log/std", "libc", "env_logger"]
log_debug = ["log/release_max_level_debug"]
log_info = ["log/release_max_level_info"]
log_warn = ["log/release_max_level_warn"]
log_error = ["log/release_max_level_error"]
